name: MERN CD

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Deploy via SSH
    uses: appleboy/ssh-action@v1.2.0
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd ~/devops-mern-todo

        git fetch origin
        git reset --hard origin/main

        docker-compose down || true
        docker-compose up -d --build
